[package]
name = "discord_token_harvester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.3.0"
rusty-leveldb = "1.0.6"
sysinfo = "0.28.4"
